services:
  postgres:
    image: postgres:15-alpine
    container_name: edubridge-postgres-dev
    environment:
      POSTGRES_DB: edubridge
      POSTGRES_USER: edubridge
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edubridge -d edubridge"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - edubridge-network

  # Additional services will be added here (Keycloak, MinIO, etc.)

volumes:
  postgres_data:
    driver: local

networks:
  edubridge-network:
    driver: bridge
